{{- if and .Values.mongo.enabled .Values.config.restore.enabled}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-restore-script
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "scripts/mongodbrestore.sh").AsConfig | indent 2 }}
---
apiVersion: v1 #??
kind: PersistentVolumeClaim
metadata:
  name: mongo-restorer
  namespace: {{ .Values.mongo.config.namespace }}
spec:
  storageClassName: {{ .Values.mongo.config.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.config.diskSize }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-restore-0
  namespace: {{ .Values.mongo.config.namespace }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.mongo.config.serviceAccount }}
      volumes:
      - name: scripts
        configMap:
          name: mongo-restore-script
          defaultMode: 0777
      # - name: mongo-snapshotter
      #   persistentVolumeClaim: #??
      #     claimName: mongo-snapshotter
      containers:
        - image: mcr.microsoft.com/azure-cli
          name: mongo-restorer
          env:
            - name: MONGO_CONNECTION_STRING
              value: "{{ .Values.mongo.config.connectionString }}"
            - name: AZURE_STORAGE_ACCOUNT
              value: "{{ .Values.mongo.config.storageAccount }}"
            - name: CONTAINER
              value: "{{ .Values.mongo.config.container }}"
            - name: BACKUP_PATH
              value: "{{ .Values.mongo.config.path }}"
            # - name: MAX_BACKUPS
            #   value: "{{ .Values.mongo.config.maxBackups }}"
            - name: MONGO_USERNAME
              value: "root"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mongo.config.secret }}"
                  key: mongodb-root-password
                  optional: false
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.mongo.config.azureSecret }}"
                  key: azure.client.default.key
                  optional: false
          volumeMounts:
            # - mountPath: "/mongodump"
            #   name: mongo-restorer
            - name: scripts
              mountPath: /scripts
          command:
            - "/scripts/mongodbrestore.sh"
            # - "tail"
            # - "-f"
            # - "/dev/null"
      restartPolicy: Never
  backoffLimit: 1

  {{- end }}