mongodb:
  enabled: false
  architecture: replicaset
  replicaCount: 3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
  auth:
     rootPassword: "1234"
postgresqlha:
  enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
  global:
    postgresql:
      password: "1234"
    pgpool:
      adminPassword: "12345"
mariadbgalera:
  enabled: false
  replicaCount: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
  rootUser:
    password: "1234"
  db:
    password: "1234"
elastic:
  enabled: false
  version: 8.6.1
  replicas: 1
  name: ic4302
kibana:
  version: 8.6.1
  replicas: 1
  name: ic4302
prometheus-elasticsearch-exporter:
  env:
    ES_USERNAME: elastic
  extraEnvSecrets:
    ES_PASSWORD:
      secret: ic4302-es-elastic-user
      key: elastic
  es:
    uri: http://ic4302-es-http:9200
    cluster_settings: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
mariadb:
  enabled: true
  architecture: replication
  primary:
    name: "master-node"
  secondary:
    name: "slave"
    replicaCount: 2
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
  auth:
    rootPassword: "1234"
postgresql:
  enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: "monitoring"
  auth:
    postgresPassword: "1234"
    database: "babynames"