apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  labels:
    app: debug-pod
spec:
  containers:
  - image: ubuntu
    env:
      - name: MARIADBHOST
        value: "databases-mariadb-master-node"
      - name: MARIADBPASSWORD
        valueFrom:
          secretKeyRef:
            name: databases-mariadb
            key: mariadb-root-password
            optional: false
      - name: MARIADBD_DB
        value: 'babynames'
      - name: MARIADBUSER
        value: 'root'
      - name: MARIADBPORT
        value: '3306'
    command:
      - "tail"
      - "-f"
      - "/dev/null"
    imagePullPolicy: IfNotPresent
    name: debug-pod