{{ if .Values.elastic.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.config.elasticConnection.name }}
  labels:
    app: {{ .Values.config.elasticConnection.nameApp }}
spec:
  version: {{.Values.elastic.version}}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  replicas: {{ .Values.config.elasticConnection.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.config.elasticConnection.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.config.elasticConnection.name }}
    spec:
      containers:
      - name: {{ .Values.config.elasticConnection.name }}
        image: {{ .Values.config.elasticConnection.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
          - name: ESENDPOINT
            value: ic4302-es-http
          - name: ESPASSWORD
            valueFrom:
              secretKeyRef:
                name: ic4302-es-elastic-user
                key: elastic
                optional: false
          - name: ESINDEX
            value: messages

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.elasticConnection.nameApp }}
  labels:
    app: {{ .Values.config.elasticConnection.nameApp }}
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000
  selector:
    app: {{ .Values.config.elasticConnection.nameApp }}
  type: NodePort

{{ end }}