{{ if .Values.mariadbgalera.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.mariadbGalera.mapName }}
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "sql/babynames.sql").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.mariadbGalera.name }}
spec:
  template:
    spec:
      volumes:
      - name: {{ .Values.config.mariadbGalera.volumeName }}
        configMap:
          name: {{ .Values.config.mariadbGalera.mapName }}
          defaultMode: 0777
      containers:
      - name: pi
        image: {{ .Values.config.mariadbGalera.image }}
        volumeMounts:
        - name: {{ .Values.config.mariadbGalera.volumeName }}
          mountPath: /scripts
        env:
          - name: MARIADBGALERAHOST
            value: "databases-mariadbgalera"
          - name: MARIADBGALERAPASS
            valueFrom:
              secretKeyRef:
                name: databases-mariadbgalera
                key: mariadb-root-password
                optional: false
        command: ["/bin/sh"]
        args: ["-c", "mysql -p$(MARIADBGALERAPASS) -u root -h$(MARIADBGALERAHOST) < /scripts/babynames.sql; mysql -p$(MARIADBGALERAPASS) -u root -h$(MARIADBGALERAHOST) -e \"SHOW DATABASES\""]
      restartPolicy: Never
  backoffLimit: 7

{{ end }}