{{ if .Values.mongodb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.mongodb.mapName }}
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "sql/world.sql").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.config.mongodb.name }}
spec:
  template:
    spec:
      volumes:
      - name: {{ .Values.config.mongodb.volumeName }}
        configMap:
          name: {{ .Values.config.mongodb.mapName }}
          defaultMode: 0777
      containers:
      - name: pi
        image: {{ .Values.config.mongodb.image }}
        volumeMounts:
        - name: {{ .Values.config.mongodb.volumeName }}
          mountPath: /scripts
        env:
          - name: MONGO_INITDB_HOST
            value: "databases-mongodb"
          - name: MONGODB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: databases-mongodb
                key: mongodb-root-password
                optional: false
        command: ["/bin/sh"]
        args: ["-c", "auth=true", "replication=true"]

        #args: ["-c", "PGPASSWORD=$(DB_PASS) psql -h $(DB_HOST) -U postgres < \"/scripts/world.sql\""]
      restartPolicy: Never
  backoffLimit: 8
{{ end }}