# template for cronjobs with rabbitmq environment
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.componente2.name }}
  labels:
    app: {{ .Values.config.componente2.name }}
spec:
  schedule: "*/2 * * * *"         
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: {{ .Values.config.componente2.name }}
            image: {{ .Values.config.componente2.image }} 
            imagePullPolicy: IfNotPresent
            env:
              - name: RABBITMQ
                value: "stateful-rabbitmq"
              - name: EVENT_INTERVAL
                value: "{{ .Values.config.componente2.interval }}"
              - name: OUTPUT_QUEUE
                value: {{ .Values.config.componente2.output_queue }}
              - name: RABBITPASS
                valueFrom:
                  secretKeyRef:
                    name: stateful-rabbitmq
                    key: rabbitmq-password
                    optional: false
            command:
            - /bin/sh
            - -c
            - date; echo Cronjob Example 2
          restartPolicy: OnFailure