apiVersion: v1
kind: ConfigMap
metadata:
  name: script-db
  namespace: {{ .Values.namespace }}
data:
{{ (.Files.Glob "sql/db.sql").AsConfig | indent 2 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-init
spec:
  template:
    spec:
      volumes:
      - name: scripts
        configMap:
          name: script-db
          defaultMode: 0777
      containers:
      - name: pi
        image: fiozelaya/mariadbclient
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        env:
          - name: MARIADBHOST
            value: "stateful-mariadb"
          - name: MARIADBPASS
            valueFrom:
              secretKeyRef:
                name: stateful-mariadb
                key: mariadb-root-password
                optional: false
          - name: MARIADBPORT
            value: "3306"
        command: ["/bin/sh"]
        args: ["-c", "mysql -p$(MARIADBPASS) -uroot -h$(MARIADBHOST) < /scripts/db.sql; mysql -p$(MARIADBPASS) -uroot -h$(MARIADBHOST) -e \"SHOW DATABASES\""]
      restartPolicy: OnFailure
  backoffLimit: 4