apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.stationsCronjob.name }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.config.stationsCronjob.name }}
            image: {{ .Values.config.stationsCronjob.image }}
            env:
              - name: MARIADBHOST
                value: "stateful-mariadb"
              - name: MARIADBPASS
                valueFrom:
                  secretKeyRef:
                    name: stateful-mariadb
                    key: mariadb-root-password
                    optional: false
          restartPolicy: OnFailure