apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.statesCronjob.name }}
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.config.statesCronjob.name }}
            image: {{ .Values.config.statesCronjob.image }}
            command: ["/bin/sh"]
          restartPolicy: OnFailure