apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.config.statesCronjob.name }}
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.config.statesCronjob.name }}
            image: {{ .Values.config.statesCronjob.image }}
            env:
              - name: MARIADBHOST
                value: "stateful-mariadb"
              - name: MARIADBPASS
                valueFrom:
                  secretKeyRef:
                    name: stateful-mariadb
                    key: mariadb-root-password
                    optional: false
          restartPolicy: OnFailure