config:
  # make one for each component and add environment variables
  # and docker container
  mariadbDb:
    mapName: script-db
    name: mariadb-init
    volumeName: scripts
    image: moisose/mariadb-client
  # This can be use for a deployment
  postgresql:
    mapName: script-db
    name: postgresql-init
    volumeName: scripts
    image: moisose/postgresql-client
  mongodb:
    mapName: script-db
    name: mongodb-init
    volumeName: scripts
    image: moisose/mongodb-client
  mariadbGalera:
    mapName: script-db
    name: mariadb-galera-init
    volumeName: scripts
    image: moisose/mariadb-galera-client
  apiMariaDBDeployment:
    replicas: 1
    name: apimariadb-deployment
    image: moisose/apimariadb
    nameApp: apimariadb-deployment
  apiMariaDBGDeployment:
    replicas: 1
    name: apimariadbga-deployment
    image: moisose/apimariadb
    nameApp: apimariadbga-deployment
  apiPostgresDeployment:
    replicas: 1
    name: apipostgres-deployment
    image: moisose/apipostgres
    nameApp: apipostgres-deployment
  apiPostgreshaDeployment:
    replicas: 1
    name: apipostgresha-deployment
    image: moisose/apipostgres
    nameApp: apipostgresha-deployment
  apiMongoDBDeployment:
    replicas: 1
    name: apimongodb-deployment
    image: moisose/apimongodb
    nameApp: nodeportApp
  elasticConnection:
    replicas: 1
    name: elastic-deployment
    image: isaac4918/elastic-search-connection
    nameApp: elastic-deployment
  # componente2:
  #   replicas: 1
  #   name: componente2
  #   output_queue: ""
  #   input_queue: ""
  #   image: username/componente2