mongodb:
  enabled: true
  auth:
    rootPassword: "1234"
mariadb:
  enabled: true
  auth:
    rootPassword: "1234"
postgresql:
  enabled: true
  auth:
    postgresPassword: "1234"
neo4j:
  enabled: false
couchdb:
  enabled: false
elastic:
  version: 8.6.1
  replicas: 1
  name: ic4302
kibana:
  version: 8.6.1
  replicas: 1
  name: ic4302
