apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elastic.name }}
spec:
  version: {{ .Values.elastic.version }}
  nodeSets:
  - name: default
    count: {{ .Values.elastic.replicas }}
    config:
      node.store.allow_mmap: false